# Generated by Django 5.2 on 2025-04-30 19:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("vimeo_id", models.CharField(max_length=50)),
                (
                    "upload_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("thumbnail_url", models.URLField(blank=True)),
                ("video_url", models.URLField(blank=True)),
                ("status", models.CharField(default="processing", max_length=20)),
            ],
            options={
                "ordering": ["-upload_date"],
            },
        ),
    ]
